### ISSUE TITLE
Blocks are not instantiated on painting

### ISSUE THREAD

**Issue by daisoto** [peartreegames/blocky-world-editor#2]
Hello, I am facing this problem in Unity 2021.3.11f1 with Blocky 0.1.7
I was following [youtube tutorial](https://youtu.be/G-SbNFa2RvU) , so I have following presets as in screenshot, but it does not draw (I am pressing left mouse button in gif). 
What am I doing wrong? It does not even throw any errors or warnings.
![blocky](https://user-images.githubusercontent.com/42536553/204288624-6ddadf59-dbfd-47e3-9d37-d9aaa2c79d6a.png)
![test](https://user-images.githubusercontent.com/42536553/204289108-9e575df3-7f11-4abe-92fe-74eaec71deb5.gif)

**Comment by bgk-** [comment]
Hey @daisoto,

You'll just need to select the Cube icon (the border will change to cyan) so it knows which item you want to place. This can be made better, maybe a warning above the palette view saying "No BlockyObject Selected"?

**Comment by bgk-** [comment]
For now I've just pushed an update which shows a debug message when painting without an object selected.

**Comment by daisoto** [comment]
Thanks, it helped!
